import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../../app/providers.dart';
import '../../../models/compliance_models.dart';
import '../../widgets/smart_navigation.dart';
import 'widgets/compliance_common.dart';

/// Reminder history (`/compliance/reminders`).
///
/// Every reminder generated by the 30-day / 7-day / expired engine plus manual
/// reminders, with channel and delivery status.
class ComplianceReminderHistoryScreen extends ConsumerStatefulWidget {
  const ComplianceReminderHistoryScreen({super.key});

  @override
  ConsumerState<ComplianceReminderHistoryScreen> createState() =>
      _ComplianceReminderHistoryScreenState();
}

class _ComplianceReminderHistoryScreenState
    extends ConsumerState<ComplianceReminderHistoryScreen> {
  ReminderType? _typeFilter;

  @override
  Widget build(BuildContext context) {
    final hospitalId = ref.watch(authStateProvider).hospitalId;
    if (hospitalId == null || hospitalId.isEmpty) {
      return Scaffold(
        appBar: SmartAppBar(title: const Text('Reminder History')),
        body: const Center(child: Text('Hospital not assigned to this user.')),
      );
    }

    final remindersAsync = ref.watch(complianceRemindersProvider(hospitalId));
    final recordsAsync = ref.watch(complianceRecordsProvider(hospitalId));

    return Scaffold(
      appBar: SmartAppBar(title: const Text('Reminder History')),
      body: Column(
        children: [
          _buildFilterBar(),
          Expanded(
            child: remindersAsync.when(
              data: (reminders) {
                final recordNames = <String, String>{
                  for (final record in recordsAsync.valueOrNull ?? const <ComplianceRecord>[])
                    record.id: record.documentName,
                };
                final filtered = _typeFilter == null
                    ? reminders
                    : reminders.where((r) => r.reminderType == _typeFilter).toList();
                if (filtered.isEmpty) {
                  return const ComplianceEmptyState(
                    icon: Icons.notifications_off_outlined,
                    message: 'No reminders yet.\n'
                        'Reminders appear automatically 30 and 7 days before expiry, and when a document expires.',
                  );
                }
                return RefreshIndicator(
                  onRefresh: () async => ref.invalidate(complianceRefreshProvider),
                  child: ListView.builder(
                    padding: const EdgeInsets.all(12),
                    itemCount: filtered.length,
                    itemBuilder: (context, index) {
                      final reminder = filtered[index];
                      return _buildReminderTile(
                        reminder,
                        recordNames[reminder.recordId] ?? 'Compliance record',
                      );
                    },
                  ),
                );
              },
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (error, _) => ComplianceEmptyState(
                icon: Icons.error_outline,
                message: 'Failed to load reminders: $error',
                actionLabel: 'Retry',
                onAction: () => ref.invalidate(complianceRefreshProvider),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFilterBar() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(12, 8, 12, 4),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: [
            _chip('All', _typeFilter == null, () => setState(() => _typeFilter = null)),
            for (final type in ReminderType.values)
              _chip(
                type.label,
                _typeFilter == type,
                () => setState(() {
                  _typeFilter = _typeFilter == type ? null : type;
                }),
                color: _typeColor(type),
              ),
          ],
        ),
      ),
    );
  }

  Widget _chip(String label, bool selected, VoidCallback onTap, {Color? color}) {
    final effectiveColor = color ?? Theme.of(context).colorScheme.primary;
    return Padding(
      padding: const EdgeInsets.only(right: 6),
      child: FilterChip(
        label: Text(label, style: const TextStyle(fontSize: 12)),
        selected: selected,
        selectedColor: effectiveColor.withValues(alpha: 0.18),
        checkmarkColor: effectiveColor,
        onSelected: (_) => onTap(),
      ),
    );
  }

  Widget _buildReminderTile(ComplianceReminderEntry reminder, String recordName) {
    final color = _typeColor(reminder.reminderType);
    final icon = reminder.reminderType == ReminderType.expired
        ? Icons.error_outline
        : reminder.reminderType == ReminderType.sevenDay
        ? Icons.warning_amber_outlined
        : reminder.reminderType == ReminderType.thirtyDay
        ? Icons.notifications_active_outlined
        : Icons.notifications_outlined;

    return Card(
      elevation: 1,
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        leading: CircleAvatar(
          backgroundColor: color.withValues(alpha: 0.12),
          child: Icon(icon, color: color, size: 20),
        ),
        title: Text(
          recordName,
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
          style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
        subtitle: Text(
          '${reminder.message ?? ''}\n'
          '${reminder.reminderType.label} • ${reminder.channel.label} • '
          '${reminder.status.toUpperCase()}',
          maxLines: 3,
          overflow: TextOverflow.ellipsis,
          style: const TextStyle(fontSize: 12),
        ),
        isThreeLine: true,
        trailing: Text(
          reminder.createdAt == null
              ? ''
              : DateFormat('dd MMM, hh:mm a').format(reminder.createdAt!.toLocal()),
          style: const TextStyle(fontSize: 11),
        ),
      ),
    );
  }

  Color _typeColor(ReminderType type) {
    switch (type) {
      case ReminderType.expired:
        return Colors.red;
      case ReminderType.sevenDay:
        return Colors.orange;
      case ReminderType.thirtyDay:
        return Colors.blue;
      case ReminderType.manual:
        return Colors.purple;
    }
  }
}
