import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../services/secure_local_storage.dart';
import 'supabase_web_config.dart';

class AppConfig {
  static bool _isInitialized = false;

  static late final SupabaseClient supabaseClient;
  static late final FlutterSecureStorage secureStorage;
  static late final SharedPreferences sharedPreferences;

  // ===========================================================================
  // Supabase Configuration
  // ---------------------------------------------------------------------------
  // Values now resolve dynamically through `SupabaseWebConfig` in this order:
  //   1. `window._env_` (web) — generated by the Vercel build script from the
  //      project environment variables (SUPABASE_URL / SUPABASE_ANON_KEY).
  //   2. `--dart-define` — the same Vercel env vars passed at build time.
  //   3. Local-development fallbacks (see supabase_web_config.dart).
  //
  // NOTE: The anon key is safe to ship to browsers (RLS keeps data protected).
  // NEVER place the service-role key in a Flutter web app.
  // ===========================================================================
  static String get supabaseUrl => SupabaseWebConfig.supabaseUrl;
  static String get supabaseAnonKey => SupabaseWebConfig.supabaseAnonKey;

  // ===========================================================================
  // Firebase Configuration
  // ---------------------------------------------------------------------------
  // Values `android/app/google-services.json` (aur Firebase Console -> Project
  // settings) se aayi hain. Inhe AppConfig mein rakhne se Firebase poore app
  // mein ek hi jagah se initialize hota hai.
  //
  // NOTE: iOS target ke liye `ios/Runner/GoogleService-Info.plist` add karo aur
  // `firebaseAppId` ko iOS app id se update karo (ya Firebase.initializeApp()
  // ko bina options ke call karo jab plist maujood ho).
  // ===========================================================================
  static const String firebaseProjectId = 'himsabdm';
  static const String firebaseApiKey =
      'AIzaSyBP89z7EOcsKgtfAgCBXE5TBkAKoarnFIA';
  static const String firebaseAuthDomain = 'himsabdm.firebaseapp.com';
  static const String firebaseStorageBucket = 'himsabdm.firebasestorage.app';
  static const String firebaseMessagingSenderId = '212987202846';
  static const String firebaseAppId =
      '1:212987202846:android:18135c94282a4c9cf18d0f';

  /// Firebase options object — `Firebase.initializeApp()` isi ko use karta hai.
  static final FirebaseOptions firebaseOptions = FirebaseOptions(
    apiKey: firebaseApiKey,
    authDomain: firebaseAuthDomain,
    projectId: firebaseProjectId,
    storageBucket: firebaseStorageBucket,
    messagingSenderId: firebaseMessagingSenderId,
    appId: firebaseAppId,
  );

  // ===========================================================================
  // ABDM (Ayushman Bharat Digital Mission) Configuration
  // ---------------------------------------------------------------------------
  // SECURITY: The ABDM Client ID and Client Secret must exist ONLY as Supabase
  // Edge Function secrets (ABDM_CLIENT_ID / ABDM_CLIENT_SECRET). They are never
  // placed in Flutter source, web/env.js, --dart-define, local storage or any
  // API response. All privileged ABDM calls go through the `abdm-gateway`
  // Edge Function, which keeps the ABDM access token server-side.
  //
  // `abdmRealModeEnabled` is the explicit environment-controlled switch:
  //   * false (default) — AbdmService runs in mock mode for local UI work.
  //   * true              — AbdmService calls the secure Edge Function for
  //                         session / Bridge / service management, and returns
  //                         clear typed errors for M1/M2/M3 operations that are
  //                         not part of this backend-foundation phase yet.
  //
  // Enable it at build time WITHOUT any secret:
  //   flutter build web --dart-define=ABDM_REAL_MODE=true
  // ===========================================================================
  static const String abdmEnvironment = 'sandbox'; // or 'production'
  static const bool abdmRealModeEnabled = bool.fromEnvironment('ABDM_REAL_MODE');

  /// True when the app is allowed to call the secure ABDM backend.
  static bool get isAbdmConfigured => abdmRealModeEnabled;

  /// Mock mode is active whenever the real backend switch is OFF. The moment
  /// the secure backend is deployed and this switch is flipped to `true`, the
  /// service routes privileged calls through the Edge Function.
  static bool get abdmMockMode => !abdmRealModeEnabled;

  // App Configuration
  static const String appName = 'HIMS - Hospital Management';
  static const String appVersion = '1.0.0';
  static const String hospitalCode = 'HIMS';

  // ===========================================================================
  // DeepSeek AI Configuration (Clinical Counseling Summarization)
  // ---------------------------------------------------------------------------
  // API key DeepSeek platform (https://platform.deepseek.com) se milega.
  // NOTE: Client-side apps mein production API key rakhna safe nahi hota —
  // production ke liye is call ko Supabase Edge Function ke through proxy karo.
  // ===========================================================================
  static String get deepSeekApiKey => SupabaseWebConfig.deepSeekApiKey;
  static const String deepSeekBaseUrl = 'https://api.deepseek.com';
  static const String deepSeekModel = 'deepseek-chat';

  static Future<void> init() async {
    // Guard: safe to call from both main.dart and providers without throwing
    // "Instance is already initialized" from Supabase.
    if (_isInitialized) return;

    // NOTE: Firebase Core is NOT initialized here anymore. Startup stays
    // fast and Firebase is initialized lazily inside
    // `PushNotificationService.initialize` (the only feature that needs FCM).
    // That path has its own duplicate-app guard and silently disables FCM
    // when Firebase is not configured for the current platform/build.

    // Initialize Secure Storage PEHLE — Supabase ka session ab secure storage
    // mein persist hoga (SharedPreferences mein JWT store nahi hoga).
    secureStorage = const FlutterSecureStorage(
      aOptions: AndroidOptions(encryptedSharedPreferences: true),
    );

    // Initialize Supabase with a secure-storage-backed session store.
    await Supabase.initialize(
      url: supabaseUrl,
      anonKey: supabaseAnonKey,
      authOptions: FlutterAuthClientOptions(
        localStorage: SecureLocalStorage(secureStorage),
      ),
    );
    supabaseClient = Supabase.instance.client;

    // Initialize Shared Preferences (non-auth preferences ke liye; auth
    // tokens isme kabhi store nahi kiye jaate).
    sharedPreferences = await SharedPreferences.getInstance();

    _isInitialized = true;
  }
}
