import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../services/secure_local_storage.dart';
import 'supabase_web_config.dart';

class AppConfig {
  static bool _isInitialized = false;

  static late final SupabaseClient supabaseClient;
  static late final FlutterSecureStorage secureStorage;
  static late final SharedPreferences sharedPreferences;

  // ===========================================================================
  // Supabase Configuration
  // ---------------------------------------------------------------------------
  // Values now resolve dynamically through `SupabaseWebConfig` in this order:
  //   1. `window._env_` (web) — generated by the Vercel build script from the
  //      project environment variables (SUPABASE_URL / SUPABASE_ANON_KEY).
  //   2. `--dart-define` — the same Vercel env vars passed at build time.
  //   3. Local-development fallbacks (see supabase_web_config.dart).
  //
  // NOTE: The anon key is safe to ship to browsers (RLS keeps data protected).
  // NEVER place the service-role key in a Flutter web app.
  // ===========================================================================
  static String get supabaseUrl => SupabaseWebConfig.supabaseUrl;
  static String get supabaseAnonKey => SupabaseWebConfig.supabaseAnonKey;

  // ===========================================================================
  // Firebase Configuration
  // ---------------------------------------------------------------------------
  // Values `android/app/google-services.json` (aur Firebase Console -> Project
  // settings) se aayi hain. Inhe AppConfig mein rakhne se Firebase poore app
  // mein ek hi jagah se initialize hota hai.
  //
  // NOTE: iOS target ke liye `ios/Runner/GoogleService-Info.plist` add karo aur
  // `firebaseAppId` ko iOS app id se update karo (ya Firebase.initializeApp()
  // ko bina options ke call karo jab plist maujood ho).
  // ===========================================================================
  static const String firebaseProjectId = 'himsabdm';
  static const String firebaseApiKey =
      'AIzaSyBP89z7EOcsKgtfAgCBXE5TBkAKoarnFIA';
  static const String firebaseAuthDomain = 'himsabdm.firebaseapp.com';
  static const String firebaseStorageBucket = 'himsabdm.firebasestorage.app';
  static const String firebaseMessagingSenderId = '212987202846';
  static const String firebaseAppId =
      '1:212987202846:android:18135c94282a4c9cf18d0f';

  /// Firebase options object — `Firebase.initializeApp()` isi ko use karta hai.
  static final FirebaseOptions firebaseOptions = FirebaseOptions(
    apiKey: firebaseApiKey,
    authDomain: firebaseAuthDomain,
    projectId: firebaseProjectId,
    storageBucket: firebaseStorageBucket,
    messagingSenderId: firebaseMessagingSenderId,
    appId: firebaseAppId,
  );

  // ===========================================================================
  // ABDM (Ayushman Bharat Digital Mission) Configuration
  // ---------------------------------------------------------------------------
  // Sandbox base URL:        https://sandbox.abdm.gov.in
  // Production base URL:     https://abdm.gov.in (switch only after UAT sign-off)
  //
  // Client ID / Secret:      Issued by ABDM Sandbox portal (https://sandbox.abdm.gov.in)
  //                          -> "Create Client" under Gateway/Health ID APIs.
  // HIP ID / HIU ID:         The facility/health-information-user IDs registered
  //                          with ABDM (used for care-context link & consent).
  //
  // NOTE: `abdmMockMode` automatically switches OFF once a real client id is
  // placed below (it only stays on while the id starts with "YOUR_").
  // ===========================================================================
  static const String abdmBaseUrl = 'https://sandbox.abdm.gov.in';
  static const String abdmClientId = 'YOUR_ABDM_CLIENT_ID';
  static const String abdmClientSecret = 'YOUR_ABDM_CLIENT_SECRET';
  static const String abdmEnvironment = 'sandbox'; // or 'production'
  static const String abdmHipId = 'YOUR_ABDM_HIP_ID';
  static const String abdmHiuId = 'YOUR_ABDM_HIU_ID';

  /// Explicit mock-mode kill switch. When `true`, `AbdmService` returns
  /// realistic fixture responses instead of calling the ABDM gateway. This
  /// lets the UI flow be developed/tested before sandbox credentials arrive.
  /// Set to `false` once real credentials are configured.
  static const bool abdmMockModeOverride = true;

  /// True when real ABDM credentials have been configured.
  static bool get isAbdmConfigured =>
      abdmClientId.isNotEmpty && !abdmClientId.startsWith('YOUR_');

  /// Mock mode is only active when the override is on AND credentials are
  /// still placeholders. The moment real credentials are added, the service
  /// starts hitting the real gateway automatically.
  static bool get abdmMockMode => abdmMockModeOverride && !isAbdmConfigured;

  // App Configuration
  static const String appName = 'HIMS - Hospital Management';
  static const String appVersion = '1.0.0';
  static const String hospitalCode = 'HIMS';

  // ===========================================================================
  // DeepSeek AI Configuration (Clinical Counseling Summarization)
  // ---------------------------------------------------------------------------
  // API key DeepSeek platform (https://platform.deepseek.com) se milega.
  // NOTE: Client-side apps mein production API key rakhna safe nahi hota —
  // production ke liye is call ko Supabase Edge Function ke through proxy karo.
  // ===========================================================================
  static String get deepSeekApiKey => SupabaseWebConfig.deepSeekApiKey;
  static const String deepSeekBaseUrl = 'https://api.deepseek.com';
  static const String deepSeekModel = 'deepseek-chat';

  static Future<void> init() async {
    // Guard: safe to call from both main.dart and providers without throwing
    // "Instance is already initialized" from Supabase.
    if (_isInitialized) return;

    // Firebase Core — push notifications (FCM) aur future Firebase services
    // ke liye pehle initialize karo. Firebase configure na ho (e.g. platform
    // support missing) toh app ka baaki flow chalta rehta hai.
    await _initFirebase();

    // Initialize Secure Storage PEHLE — Supabase ka session ab secure storage
    // mein persist hoga (SharedPreferences mein JWT store nahi hoga).
    secureStorage = const FlutterSecureStorage(
      aOptions: AndroidOptions(encryptedSharedPreferences: true),
    );

    // Initialize Supabase with a secure-storage-backed session store.
    await Supabase.initialize(
      url: supabaseUrl,
      anonKey: supabaseAnonKey,
      authOptions: FlutterAuthClientOptions(
        localStorage: SecureLocalStorage(secureStorage),
      ),
    );
    supabaseClient = Supabase.instance.client;

    // Initialize Shared Preferences (non-auth preferences ke liye; auth
    // tokens isme kabhi store nahi kiye jaate).
    sharedPreferences = await SharedPreferences.getInstance();

    _isInitialized = true;
  }

  /// Firebase ko explicitly provided options ke saath initialize karta hai.
  ///
  /// Fail hone par bhi app chalti rehti hai — `PushNotificationService`
  /// Firebase missing hone par khud ko silently disable kar leta hai.
  static Future<void> _initFirebase() async {
    try {
      await _initializeFirebaseApp();
    } catch (e) {
      // ignore: avoid_print — startup ke waqt logger abhi ready nahi hota.
      print('Firebase initialization skipped: $e');
    }
  }

  /// `Firebase.initializeApp()` ko cross-platform safe tareeke se call karta
  /// hai. NOTE: web par `Firebase.apps.isEmpty` check khud hi
  /// `core/not-initialized` throw kar deta hai (firebase_core_web ka
  /// `guardNotInitialized`), isliye pehle check karne ke bajaye seedha
  /// initialize karte hain aur `duplicate-app` (already initialized) ko
  /// ignore kar dete hain.
  static Future<void> _initializeFirebaseApp() async {
    try {
      await Firebase.initializeApp(options: firebaseOptions);
    } on FirebaseException catch (e) {
      if (e.code != 'duplicate-app') rethrow;
    }
  }
}
